/** @license
 * DHTML Snowstorm! JavaScript-based snow for web pages
 * Making it snow on the internets since 2003. You're welcome.
 * -----------------------------------------------------------
 * Modified to only trigger during certain months of the year, aswell as change some default configurations.
 * -----------------------------------------------------------
 * Version 1.44.20131215 (Previous rev: 1.44.20131208)
 * Copyright (c) 2007, Scott Schiller. All rights reserved.
 * Code provided under the BSD License
 * http://schillmania.com/projects/snowstorm/license.txt
 */
var snowStorm=function(d,e){function l(c,g){isNaN(g)&&(g=0);return Math.random()*c+g}function D(){d.setTimeout(function(){a.start(!0)},20);a.events.remove(p?e:d,"mousemove",D)}function E(){a.excludeMobile&&K||D();a.events.remove(d,"load",E)}this.excludeMobile=this.autoStart=!0;this.flakesMax=128;this.flakesMaxActive=64;this.animationInterval=33;this.useGPU=!0;this.className=null;this.excludeMobile=!0;this.flakeBottom=null;this.followMouse=!1;this.snowColor="#fff";this.snowCharacter="&bull;";this.snowStick=
!1;this.targetElement=null;this.usePixelPosition=this.usePositionFixed=this.useTwinkleEffect=this.useMeltEffect=!1;this.freezeOnBlur=!0;this.flakeRightOffset=this.flakeLeftOffset=0;this.flakeHeight=this.flakeWidth=8;this.vMaxX=5;this.vMaxY=4;this.zIndex=0;var a=this,p=navigator.userAgent.match(/msie/i),t=navigator.userAgent.match(/msie 6/i),K=navigator.userAgent.match(/mobile|opera m(ob|in)/i),u=p&&"BackCompat"===e.compatMode||t,k=null,q=null,m=null,r=null,v=null,F=null,G=null,y=1,w=!1,z=!1;a:{try{e.createElement("div").style.opacity=
"0.5"}catch(c){var A=!1;break a}A=!0}var H=!1,I=e.createDocumentFragment();var B=function(){function c(h){d.setTimeout(h,1E3/(a.animationInterval||20))}function g(h){return void 0!==n.style[h]?h:null}var f=d.requestAnimationFrame||d.webkitRequestAnimationFrame||d.mozRequestAnimationFrame||d.oRequestAnimationFrame||d.msRequestAnimationFrame||c;var b=f?function(){return f.apply(d,arguments)}:null;var n=e.createElement("div");b={transform:{ie:g("-ms-transform"),moz:g("MozTransform"),opera:g("OTransform"),
webkit:g("webkitTransform"),w3:g("transform"),prop:null},getAnimationFrame:b};b.transform.prop=b.transform.w3||b.transform.moz||b.transform.webkit||b.transform.ie||b.transform.opera;n=null;return b}();this.timer=null;this.flakes=[];this.active=this.disabled=!1;this.meltFrameCount=20;this.meltFrames=[];this.setXY=function(c,g,f){if(!c)return!1;a.usePixelPosition||z?(c.style.left=g-a.flakeWidth+"px",c.style.top=f-a.flakeHeight+"px"):u?(c.style.right=100-g/k*100+"%",c.style.top=Math.min(f,v-a.flakeHeight)+
"px"):a.flakeBottom?(c.style.right=100-g/k*100+"%",c.style.top=Math.min(f,v-a.flakeHeight)+"px"):(c.style.right=100-g/k*100+"%",c.style.bottom=100-f/m*100+"%")};this.events=function(){function c(h){h=b.call(h);var x=h.length;f?(h[1]="on"+h[1],3<x&&h.pop()):3===x&&h.push(!1);return h}function g(h,x){var C=h.shift(),J=[n[x]];if(f)C[J](h[0],h[1]);else C[J].apply(C,h)}var f=!d.addEventListener&&d.attachEvent,b=Array.prototype.slice,n={add:f?"attachEvent":"addEventListener",remove:f?"detachEvent":"removeEventListener"};
return{add:function(){g(c(arguments),"add")},remove:function(){g(c(arguments),"remove")}}}();this.randomizeWind=function(){var c=l(a.vMaxX,.2);F=1===parseInt(l(2),10)?-1*c:c;G=l(a.vMaxY,.2);if(this.flakes)for(c=0;c<this.flakes.length;c++)this.flakes[c].active&&this.flakes[c].setVelocities()};this.scrollHandler=function(){var c;r=a.flakeBottom?0:parseInt(d.scrollY||e.documentElement.scrollTop||(u?e.body.scrollTop:0),10);isNaN(r)&&(r=0);if(!w&&!a.flakeBottom&&a.flakes)for(c=0;c<a.flakes.length;c++)0===
a.flakes[c].active&&a.flakes[c].stick()};this.resizeHandler=function(){d.innerWidth||d.innerHeight?(k=d.innerWidth-16-a.flakeRightOffset,m=a.flakeBottom||d.innerHeight):(k=(e.documentElement.clientWidth||e.body.clientWidth||e.body.scrollWidth)-(p?0:8)-a.flakeRightOffset,m=a.flakeBottom||e.documentElement.clientHeight||e.body.clientHeight||e.body.scrollHeight);v=e.body.offsetHeight;q=parseInt(k/2,10)};this.resizeHandlerAlt=function(){k=a.targetElement.offsetWidth-a.flakeRightOffset;m=a.flakeBottom||
a.targetElement.offsetHeight;q=parseInt(k/2,10);v=e.body.offsetHeight};this.freeze=function(){if(a.disabled)return!1;a.disabled=1;a.timer=null};this.resume=function(){if(a.disabled)a.disabled=0;else return!1;a.timerInit()};this.toggleSnow=function(){a.flakes.length?(a.active=!a.active,a.active?(a.show(),a.resume()):(a.stop(),a.freeze())):a.start()};this.stop=function(){var c;this.freeze();for(c=0;c<this.flakes.length;c++)this.flakes[c].o.style.display="none";a.events.remove(d,"scroll",a.scrollHandler);
a.events.remove(d,"resize",a.resizeHandler);a.freezeOnBlur&&(p?(a.events.remove(e,"focusout",a.freeze),a.events.remove(e,"focusin",a.resume)):(a.events.remove(d,"blur",a.freeze),a.events.remove(d,"focus",a.resume)))};this.show=function(){var c;for(c=0;c<this.flakes.length;c++)this.flakes[c].o.style.display="block"};this.SnowFlake=function(c,g,f){var b=this;this.type=c;this.x=g||parseInt(l(k-20),10);this.y=isNaN(f)?-l(m)-12:f;this.vY=this.vX=null;this.vAmpTypes=[1,1.2,1.4,1.6,1.8];this.vAmp=this.vAmpTypes[this.type]||
1;this.melting=!1;this.meltFrameCount=a.meltFrameCount;this.meltFrames=a.meltFrames;this.twinkleFrame=this.meltFrame=0;this.active=1;this.fontSize=10+this.type/5*10;this.o=e.createElement("div");this.o.innerHTML=a.snowCharacter;a.className&&this.o.setAttribute("class",a.className);this.o.style.color=a.snowColor;this.o.style.position=w?"fixed":"absolute";a.useGPU&&B.transform.prop&&(this.o.style[B.transform.prop]="translate3d(0px, 0px, 0px)");this.o.style.width=a.flakeWidth+"px";this.o.style.height=
a.flakeHeight+"px";this.o.style.fontFamily="arial,verdana";this.o.style.cursor="default";this.o.style.overflow="hidden";this.o.style.fontWeight="normal";this.o.style.zIndex=a.zIndex;I.appendChild(this.o);this.refresh=function(){if(isNaN(b.x)||isNaN(b.y))return!1;a.setXY(b.o,b.x,b.y)};this.stick=function(){u||a.targetElement!==e.documentElement&&a.targetElement!==e.body?b.o.style.top=m+r-a.flakeHeight+"px":a.flakeBottom?b.o.style.top=a.flakeBottom+"px":(b.o.style.display="none",b.o.style.top="auto",
b.o.style.bottom="0%",b.o.style.position="fixed",b.o.style.display="block")};this.vCheck=function(){0<=b.vX&&.2>b.vX?b.vX=.2:0>b.vX&&-.2<b.vX&&(b.vX=-.2);0<=b.vY&&.2>b.vY&&(b.vY=.2)};this.move=function(){var n=b.vX*y;b.x+=n;b.y+=b.vY*b.vAmp;b.x>=k||k-b.x<a.flakeWidth?b.x=0:0>n&&b.x-a.flakeLeftOffset<-a.flakeWidth&&(b.x=k-a.flakeWidth-1);b.refresh();m+r-b.y+a.flakeHeight<a.flakeHeight?(b.active=0,a.snowStick?b.stick():b.recycle()):(a.useMeltEffect&&b.active&&3>b.type&&!b.melting&&.998<Math.random()&&
(b.melting=!0,b.melt()),a.useTwinkleEffect&&(0>b.twinkleFrame?.97<Math.random()&&(b.twinkleFrame=parseInt(8*Math.random(),10)):(b.twinkleFrame--,A?b.o.style.opacity=b.twinkleFrame&&0===b.twinkleFrame%2?0:1:b.o.style.visibility=b.twinkleFrame&&0===b.twinkleFrame%2?"hidden":"visible")))};this.animate=function(){b.move()};this.setVelocities=function(){b.vX=F+l(.12*a.vMaxX,.1);b.vY=G+l(.12*a.vMaxY,.1)};this.setOpacity=function(n,h){if(!A)return!1;n.style.opacity=h};this.melt=function(){a.useMeltEffect&&
b.melting?b.meltFrame<b.meltFrameCount?(b.setOpacity(b.o,b.meltFrames[b.meltFrame]),b.o.style.fontSize=b.fontSize-b.meltFrame/b.meltFrameCount*b.fontSize+"px",b.o.style.lineHeight=a.flakeHeight+2+b.meltFrame/b.meltFrameCount*a.flakeHeight*.75+"px",b.meltFrame++):b.recycle():b.recycle()};this.recycle=function(){b.o.style.display="none";b.o.style.position=w?"fixed":"absolute";b.o.style.bottom="auto";b.setVelocities();b.vCheck();b.meltFrame=0;b.melting=!1;b.setOpacity(b.o,1);b.o.style.padding="0px";
b.o.style.margin="0px";b.o.style.fontSize=b.fontSize+"px";b.o.style.lineHeight=a.flakeHeight+2+"px";b.o.style.textAlign="center";b.o.style.verticalAlign="baseline";b.x=parseInt(l(k-a.flakeWidth-20),10);b.y=parseInt(-1*l(m),10)-a.flakeHeight;b.refresh();b.o.style.display="block";b.active=1};this.recycle();this.refresh()};this.snow=function(){var c=0,g;var f=0;for(g=a.flakes.length;f<g;f++)1===a.flakes[f].active&&(a.flakes[f].move(),c++),a.flakes[f].melting&&a.flakes[f].melt();c<a.flakesMaxActive&&
(c=a.flakes[parseInt(l(a.flakes.length),10)],0===c.active&&(c.melting=!0));a.timer&&B.getAnimationFrame(a.snow)};this.mouseMove=function(c){if(!a.followMouse)return!0;c=parseInt(c.clientX,10);c<q?y=-2+c/q*2:(c-=q,y=c/q*2)};this.createSnow=function(c,g){var f;for(f=0;f<c;f++)if(a.flakes[a.flakes.length]=new a.SnowFlake(parseInt(l(6),10)),g||f>a.flakesMaxActive)a.flakes[a.flakes.length-1].active=-1;a.targetElement.appendChild(I)};this.timerInit=function(){a.timer=!0;a.snow()};this.init=function(){var c;
for(c=0;c<a.meltFrameCount;c++)a.meltFrames.push(1-c/a.meltFrameCount);a.randomizeWind();a.createSnow(a.flakesMax);a.events.add(d,"resize",a.resizeHandler);a.events.add(d,"scroll",a.scrollHandler);a.freezeOnBlur&&(p?(a.events.add(e,"focusout",a.freeze),a.events.add(e,"focusin",a.resume)):(a.events.add(d,"blur",a.freeze),a.events.add(d,"focus",a.resume)));a.resizeHandler();a.scrollHandler();a.followMouse&&a.events.add(p?e:d,"mousemove",a.mouseMove);a.animationInterval=Math.max(20,a.animationInterval);
a.timerInit()};this.start=function(c){if(!H)H=!0;else if(c)return!0;if("string"===typeof a.targetElement&&(c=a.targetElement,a.targetElement=e.getElementById(c),!a.targetElement))throw Error('Snowstorm: Unable to get targetElement "'+c+'"');a.targetElement||(a.targetElement=e.body||e.documentElement);a.targetElement!==e.documentElement&&a.targetElement!==e.body&&(a.resizeHandler=a.resizeHandlerAlt,a.usePixelPosition=!0);a.resizeHandler();a.usePositionFixed=a.usePositionFixed&&!u&&!a.flakeBottom;if(d.getComputedStyle)try{z=
"relative"===d.getComputedStyle(a.targetElement,null).getPropertyValue("position")}catch(g){z=!1}w=a.usePositionFixed;k&&m&&!a.disabled&&(a.init(),a.active=!0)};t=(new Date).getMonth();!a.autoStart||11!=t&&0!=t||a.events.add(d,"load",E,!1);return this}(window,document);